# Generated by Django 5.2.9 on 2025-12-14 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Equipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(help_text="Nome da equipe", max_length=200)),
                (
                    "descricao",
                    models.TextField(
                        blank=True,
                        help_text="Descrição da equipe e suas responsabilidades",
                        null=True,
                    ),
                ),
                (
                    "data_criacao",
                    models.DateField(
                        auto_now_add=True, help_text="Data de criação da equipe"
                    ),
                ),
            ],
            options={
                "verbose_name": "Equipe",
                "verbose_name_plural": "Equipes",
                "ordering": ["projeto", "nome"],
            },
        ),
    ]
