# Generated by Django 5.2.9 on 2025-12-14 00:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("equipe", "0001_initial"),
        ("projetos", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="equipe",
            name="lider",
            field=models.OneToOneField(
                blank=True,
                help_text="Líder responsável pela equipe (um usuário pode liderar no máximo uma equipe)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="equipe_liderada",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="equipe",
            name="membros",
            field=models.ManyToManyField(
                blank=True,
                help_text="Membros da equipe",
                related_name="equipes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="equipe",
            name="projeto",
            field=models.ForeignKey(
                help_text="Projeto ao qual esta equipe pertence",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="equipes",
                to="projetos.projeto",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="equipe",
            unique_together={("nome", "projeto")},
        ),
    ]
