# Generated by Django 5.2.9 on 2025-12-10 14:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.CharField(max_length=1000)),
                ('data_inicio', models.DateField(default=datetime.date.today)),
                ('data_fim_prevista', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('nao_iniciado', 'Não Iniciado'), ('em_andamento', 'Em Andamento'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='nao_iniciado', max_length=30)),
            ],
        ),
    ]
