# Generated by Django 5.2.9 on 2025-12-16 15:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0002_alter_projeto_descricao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipacaoProjeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_entrada', models.DateField(auto_now_add=True, help_text='Data em que o usuário entrou no projeto')),
                ('data_saida', models.DateField(blank=True, help_text='Data em que o usuário saiu do projeto', null=True)),
                ('ativo', models.BooleanField(default=True, help_text='Indica se o usuário ainda está ativo no projeto')),
                ('projeto', models.ForeignKey(help_text='Projeto do qual o usuário participa', on_delete=django.db.models.deletion.CASCADE, to='projetos.projeto')),
                ('usuario', models.ForeignKey(help_text='Usuário participante do projeto', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Participação em Projeto',
                'verbose_name_plural': 'Participações em Projetos',
                'ordering': ['-data_entrada'],
                'unique_together': {('usuario', 'projeto')},
            },
        ),
        migrations.AddField(
            model_name='projeto',
            name='participantes',
            field=models.ManyToManyField(blank=True, help_text='Usuários que participam nesse projeto', related_name='projetos', through='projetos.ParticipacaoProjeto', to=settings.AUTH_USER_MODEL),
        ),
    ]
