# Generated by Django 5.2.9 on 2025-12-16 15:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0003_participacaoprojeto_projeto_participantes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='participacaoprojeto',
            name='is_leader',
            field=models.BooleanField(default=False, help_text='Indica se o usuário é o líder da equipe do projeto'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='professor',
            field=models.ForeignKey(blank=True, help_text='Professor orientador do projeto', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projetos_orientados', to=settings.AUTH_USER_MODEL),
        ),
    ]
