# Generated by Django 5.2.9 on 2025-12-16 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0004_participacaoprojeto_is_leader_projeto_professor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Coordenador que criou o projeto', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projetos_criados', to=settings.AUTH_USER_MODEL),
        ),
    ]
