# Generated by Django 5.2.9 on 2025-12-16 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0005_projeto_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Se True, o projeto será visível para visitantes sem autenticação'),
        ),
    ]
