# Generated by Django 5.2.9 on 2025-12-16 15:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projetos', '0003_participacaoprojeto_projeto_participantes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome da equipe', max_length=200)),
                ('descricao', models.TextField(blank=True, help_text='Descrição da equipe e suas responsabilidades', null=True)),
                ('data_criacao', models.DateField(auto_now_add=True, help_text='Data de criação da equipe')),
                ('lider', models.OneToOneField(blank=True, help_text='Líder responsável pela equipe (um usuário pode liderar no máximo uma equipe)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipe_liderada', to=settings.AUTH_USER_MODEL)),
                ('membros', models.ManyToManyField(blank=True, help_text='Membros da equipe', related_name='equipes', to=settings.AUTH_USER_MODEL)),
                ('projeto', models.ForeignKey(help_text='Projeto ao qual esta equipe pertence', on_delete=django.db.models.deletion.CASCADE, related_name='equipes', to='projetos.projeto')),
            ],
            options={
                'verbose_name': 'Equipe',
                'verbose_name_plural': 'Equipes',
                'ordering': ['projeto', 'nome'],
                'unique_together': {('nome', 'projeto')},
            },
        ),
    ]
